{{- if .Values.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "quickwit.fullname" . }}
  labels:
    {{- include "quickwit.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.serviceMonitor.endpoints }}
  endpoints:
{{ toYaml .Values.serviceMonitor.endpoints | indent 2 }}
  {{- end }}
  jobLabel: app.kubernetes.io/instance
  selector:
    matchLabels:
      {{- include "quickwit.selectorLabels" . | nindent 6 }}
{{- end }}